# Generated by Django 3.2.3 on 2024-01-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables_carga_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto_estatal', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('sar', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('cesantia', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('infonavit', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variables_imss_patronal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota_fija', models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True)),
                ('cf_patron', models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True)),
                ('cf_obrero', models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True)),
                ('pd_patron', models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True)),
                ('pd_obrero', models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True)),
                ('gmp_patron', models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True)),
                ('gmp_obrero', models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True)),
                ('iv_patron', models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True)),
                ('iv_obrero', models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True)),
                ('gps_patron', models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True)),
            ],
        ),
    ]
