# Generated by Django 4.1.1 on 2023-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosbancarios',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicaldatosbancarios',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='status',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bonos',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='costo',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='economicos',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalbonos',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcosto',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaleconomicos',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalperfil',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalvacaciones',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
