# Generated by Django 3.2.3 on 2023-07-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20230712_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvacaciones',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='comentario_rh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
