# Generated by Django 4.2.9 on 2024-01-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_variables_carga_social_variables_imss_patronal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatus',
            name='fecha_alta_imss',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='fecha_alta_imss',
            field=models.DateField(blank=True, null=True),
        ),
    ]
