# Generated by Django 3.2.3 on 2023-07-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20230713_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='asunto1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='asunto2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='asunto3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='asunto4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='asunto5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='asunto6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='estado1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='estado2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='estado3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='estado4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='estado5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos_encomendados',
            name='estado6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
