# Generated by Django 4.2.9 on 2024-01-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_historicalstatus_fecha_alta_imss_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['nivel']},
        ),
    ]
