# Generated by Django 4.2.9 on 2024-01-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_nivel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoperfil',
            name='esquema_bono',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
