# Generated by Django 4.1.1 on 2023-06-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_datosbancarios_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_vacaciones',
            name='comentario_rh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
