# Generated by Django 3.2.3 on 2023-07-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20230713_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajos_encomendados',
            name='asunto11',
        ),
        migrations.RemoveField(
            model_name='trabajos_encomendados',
            name='asunto12',
        ),
        migrations.RemoveField(
            model_name='trabajos_encomendados',
            name='estado11',
        ),
        migrations.RemoveField(
            model_name='trabajos_encomendados',
            name='estado12',
        ),
    ]
