# Generated by Django 4.2.9 on 2024-02-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_historicalregistropatronal'),
    ]

    operations = [
        migrations.AddField(
            model_name='costo',
            name='total_bono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalcosto',
            name='total_bono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
