# Generated by Django 4.2.9 on 2024-02-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_costo_total_bono_historicalcosto_total_bono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costo',
            old_name='total_bono',
            new_name='bono_total',
        ),
        migrations.RenameField(
            model_name='historicalcosto',
            old_name='total_bono',
            new_name='bono_total',
        ),
    ]
