# Generated by Django 4.1.1 on 2023-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_remove_solicitud_vacaciones_asunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatus',
            name='fecha_cedula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='fecha_cedula',
            field=models.DateField(blank=True, null=True),
        ),
    ]
