# Generated by Django 4.2.9 on 2024-02-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_rename_total_bono_costo_bono_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
    ]
