# Generated by Django 4.2.9 on 2024-02-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_alter_status_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbancarios',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status'),
        ),
    ]
