# Generated by Django 4.1.1 on 2023-08-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_historicaldatos_baja_datos_baja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_baja',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicaldatos_baja',
            name='status',
        ),
        migrations.AddField(
            model_name='datos_baja',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
        migrations.AddField(
            model_name='historicaldatos_baja',
            name='perfil',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.perfil'),
        ),
    ]
