# Generated by Django 4.2.9 on 2024-02-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_alter_datosbancarios_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status'),
        ),
    ]
