# Generated by Django 4.2.9 on 2024-02-19 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_alter_costo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='proyecto.perfil'),
        ),
    ]
