# Generated by Django 4.2.9 on 2024-02-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_alter_status_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacaciones_dias_tomados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('dia_inhabil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion')),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.vacaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Economicos_dia_tomado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.economicos')),
            ],
        ),
    ]
