# Generated by Django 4.2.9 on 2024-02-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_vacaciones_dias_tomados_economicos_dia_tomado'),
    ]

    operations = [
        migrations.AddField(
            model_name='costo',
            name='laborados_imss',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='costo',
            name='sdi_imss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalcosto',
            name='laborados_imss',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalcosto',
            name='sdi_imss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
