# Generated by Django 4.2.9 on 2024-03-09 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_costo_laborados_imss_costo_sdi_imss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laborados', models.IntegerField(default=0, null=True)),
                ('laborados_imss', models.IntegerField(default=0, null=True)),
                ('seccion', models.CharField(max_length=50, null=True)),
                ('amortizacion_infonavit', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('fonacot', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('neto_catorcenal_sin_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('complemento_salario_catorcenal', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('sueldo_diario', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('sdi_imss', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('sdi', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('apoyo_de_pasajes', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('imms_obrero_patronal', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('apoyo_vist_familiar', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('estancia', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('renta', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('apoyo_estudios', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('amv', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('gasolina', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('campamento', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('total_deduccion', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('sueldo_mensual_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('complemento_salario_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('sueldo_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('sueldo_mensual_sdi', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('total_percepciones_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('impuesto_estatal', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('sar', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('cesantia', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('infonavit', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('isr', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('lim_inferior', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('excedente', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('tasa', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('impuesto_marginal', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('cuota_fija', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('subsidio', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('total_apoyosbonos_empleadocomp', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('total_prima_vacacional', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('bono_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('total_apoyosbonos_agregcomis', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('comision_complemeto_salario_bonos', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('total_costo_empresa', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('ingreso_mensual_neto_empleado', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
                ('editado', models.CharField(blank=True, max_length=50)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status')),
            ],
        ),
    ]
