# Generated by Django 4.1.1 on 2023-09-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_remove_datos_baja_demanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatus',
            name='escuela',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='lugar_nacimiento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='numero_ine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='escuela',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='lugar_nacimiento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='numero_ine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstatus',
            name='profesion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='profesion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
