# Generated by Django 4.1.1 on 2023-09-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_historicalstatus_escuela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstatus',
            name='escuela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstatus',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstatus',
            name='numero_ine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='escuela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='numero_ine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
