# Generated by Django 4.2.9 on 2024-03-31 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_costoanterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_economicos',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
        migrations.AddField(
            model_name='solicitud_vacaciones',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
        migrations.AlterField(
            model_name='solicitud_economicos',
            name='comentario',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='comentario_rh',
            field=models.TextField(null=True),
        ),
    ]
