# Generated by Django 4.2.7 on 2024-03-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_alter_historicalbonos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_economicos',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
    ]
