# Generated by Django 4.2.9 on 2024-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_solicitud_economicos_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvacaciones',
            name='comentario',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
