# Generated by Django 4.1.1 on 2024-01-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_alter_historicalstatus_escuela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstatus',
            name='domicilio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='domicilio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
