# Generated by Django 4.2.9 on 2024-03-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_alter_historicalbonos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_economicos',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
    ]
