# Generated by Django 4.2.9 on 2024-04-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_alter_historicalvacaciones_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacaciones_dias_tomados',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
