# Generated by Django 4.2.9 on 2024-03-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_solicitud_economicos_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_economicos',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
    ]
