# Generated by Django 4.2.9 on 2024-04-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_alter_vacaciones_dias_tomados_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_economicos',
            name='autorizar_jefe',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_economicos',
            name='observacion_jefe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='solicitud_economicos',
            name='perfil_gerente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gerente', to='proyecto.perfil'),
        ),
    ]
