# Generated by Django 4.2.9 on 2024-01-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_alter_historicalbonos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='nivel',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
