# Generated by Django 4.2.9 on 2024-03-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_alter_solicitud_economicos_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_vacaciones',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
    ]
