# Generated by Django 4.2.9 on 2024-04-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_solicitud_economicos_autorizar_jefe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicos_dia_tomado',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
