# Generated by Django 4.2.9 on 2024-03-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0020_solicitud_vacaciones_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='comentario_rh',
            field=models.TextField(null=True),
        ),
    ]
