# Generated by Django 4.1.1 on 2024-01-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0021_registropatronal_editado_registropatronal_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables_carga_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto_estatal', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('sar', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('cesantia', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('infonavit', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variables_imss_patronal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_patron', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('pd_obrero', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('gmp_patron', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('gmp_obrero', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('riesgo_trabajo', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('iv_patron', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('iv_obrero', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('gps_patron', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='salariodatos',
            name='comision_bonos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salariodatos',
            name='dias_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salariodatos',
            name='dias_quincena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
