# Generated by Django 4.1.1 on 2024-01-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0022_variables_carga_social_variables_imss_patronal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables_imss_patronal',
            name='gmp_obrero',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variables_imss_patronal',
            name='gmp_patron',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variables_imss_patronal',
            name='gps_patron',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variables_imss_patronal',
            name='iv_obrero',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variables_imss_patronal',
            name='iv_patron',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variables_imss_patronal',
            name='pd_obrero',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variables_imss_patronal',
            name='pd_patron',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variables_imss_patronal',
            name='riesgo_trabajo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
