# Generated by Django 4.1.1 on 2024-01-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0023_alter_variables_imss_patronal_gmp_obrero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variables_imss_patronal',
            name='riesgo_trabajo',
        ),
    ]
