# Generated by Django 4.2.9 on 2024-05-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0024_alter_historicalbonos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables_imss_patronal',
            name='cav_patron',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
