# Generated by Django 4.2.7 on 2024-05-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0025_alter_historicalbonos_options_and_more'),
        ('proyecto', '0025_variables_imss_patronal_cav_patron'),
    ]

    operations = [
    ]
