# Generated by Django 4.1.1 on 2024-01-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0025_salariodatos_prima_vacacional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costo',
            name='total_prima_vacacional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalcosto',
            name='total_prima_vacacional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
