# Generated by Django 4.2.9 on 2024-05-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0031_alter_historicalbonos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catorcenas',
            name='fecha_final',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='catorcenas',
            name='fecha_inicial',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
