# Generated by Django 4.2.7 on 2024-06-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0038_alter_historicalbonos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaSubsidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liminf', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('limsup', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
            ],
        ),
    ]
