# Generated by Django 4.2.7 on 2024-07-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0045_alter_historicalbonos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costo',
            name='apoyo_salud',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalcosto',
            name='apoyo_salud',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
