# Generated by Django 4.2.9 on 2024-07-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0046_alter_historicalbonos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoperfil',
            name='prenomina',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
