# Generated by Django 4.2.9 on 2024-07-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0046_costo_apoyo_salud_historicalcosto_apoyo_salud'),
        ('proyecto', '0047_tipoperfil_prenomina'),
    ]

    operations = [
    ]
