# Generated by Django 4.2.9 on 2024-07-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0048_merge_20240722_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='costoanterior',
            name='apoyo_salud',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
