# Generated by Django 4.2.9 on 2025-07-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0053_remove_userdatos_cargo_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatos',
            name='vis_distritos',
            field=models.ManyToManyField(blank=True, related_name='vis_distritos', to='proyecto.distrito'),
        ),
    ]
