# Generated by Django 4.2.9 on 2025-07-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0055_tipoperfil_crear_bonos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoperfil',
            name='crear_bonos',
            field=models.BooleanField(default=False),
        ),
    ]
