# Generated by Django 4.2.9 on 2025-07-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0056_alter_tipoperfil_crear_bonos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoperfil',
            name='superintendente',
            field=models.BooleanField(default=False),
        ),
    ]
