# Generated by Django 4.2.7 on 2023-11-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0017_alter_historicalbonos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Esquema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('Esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esquema.esquema')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('esquema_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esquema.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.distrito')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('url', models.FileField(max_length=254, upload_to='archivos/')),
                ('esquema_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esquema.esquemasolicitado')),
                ('tipo_requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esquema.tiporequerimiento')),
            ],
        ),
        migrations.AddField(
            model_name='esquemasolicitado',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esquema.solicitud'),
        ),
        migrations.AddField(
            model_name='esquemasolicitado',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
        migrations.AddField(
            model_name='esquema',
            name='esquema_subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esquema.subcategoria'),
        ),
        migrations.AddField(
            model_name='esquema',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.puesto'),
        ),
    ]
