# Generated by Django 4.2.9 on 2024-01-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0002_puesto_alter_bono_puesto_alter_bonosolicitado_puesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puesto',
            old_name='nombre',
            new_name='puesto',
        ),
    ]
