# Generated by Django 4.2.9 on 2024-01-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0003_rename_nombre_puesto_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='complete_bono',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='complete_requerimieto',
            field=models.BooleanField(default=False),
        ),
    ]
