# Generated by Django 4.2.9 on 2024-01-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0004_solicitud_complete_bono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='complete_requerimieto',
            new_name='complete',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='complete_requerimiento',
            field=models.BooleanField(default=False),
        ),
    ]
