# Generated by Django 4.2.9 on 2024-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0006_solicitud_fecha_autorizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='soporte',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
