# Generated by Django 4.2.9 on 2024-03-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0007_subcategoria_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='puesto',
            field=models.CharField(max_length=100),
        ),
    ]
