# Generated by Django 4.2.7 on 2024-06-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0008_alter_puesto_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonosolicitado',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
