# Generated by Django 4.2.7 on 2024-07-03 22:25

import django.core.validators
from django.db import migrations, models
import esquema.models


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0009_alter_bonosolicitado_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='url',
            field=models.FileField(unique=True, upload_to='bonos/', validators=[esquema.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xls', 'xlsx'])]),
        ),
    ]
