# Generated by Django 4.2.9 on 2024-07-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0010_alter_requerimiento_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='puesto',
            field=models.CharField(max_length=200),
        ),
    ]
