# Generated by Django 4.2.9 on 2024-07-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0011_alter_puesto_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='soporte',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
