# Generated by Django 4.2.9 on 2024-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0012_alter_subcategoria_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
