"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r9fy(pk86$+m$yra4u*dua2%u(8xp9e-t^(3q3ibft-oj6c+zk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #True es para ver la pantalla amarilla, False para ver el 404

ALLOWED_HOSTS = ['www.vordcab.cloud','vordcab.cloud','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard.apps.DashboardConfig',
    'proyecto.apps.ProyectoConfig',
    'apiapp.apps.ApiappConfig',
    'user.apps.UserConfig',
    'rest_framework',
    'rest_framework.authtoken',
#    'djoser',


# Extensions - installed with pip3 / requirements.txt
    'django_extensions',
    'widget_tweaks',
    'simple_history',
    'django_filters',
    "django_htmx",
    'crispy_forms',
    'esquema',
    'revisar',
    'prenomina',
    'calculos',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'user.middleware.LogUserAccessMiddleware',
    'user.middleware.Handle404Middleware',
    
]

AUTHENTICATION_BACKENDS = [
    'user.backends.EmailBackend',
]


ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.contadores_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DATABASE_NAME'),
	    'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': 'localhost',
        'PORT': '3306',
	}
}
# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = (BASE_DIR/'static/images')

MEDIA_URL = '/images/'

STATICFILES_DIRS = [
    BASE_DIR /'static'
    ]

STATIC_ROOT = (BASE_DIR/'assert/')

#LOGIN_REDIRECT_URL ='index'
LOGIN_REDIRECT_URL = 'seleccionar_perfil'

#Configuracion de los archivos cargados por los usuarios
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.gmail.com"
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER="victorjosh02@gmail.com"
EMAIL_HOST_PASSWORD="ppysupnditwwccde"
"""

EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_USE_TLS=True
EMAIL_PORT = '2525'
EMAIL_HOST_USER = '4cdcd76acec7dc'
EMAIL_HOST_PASSWORD = 'fa643eca5fde05'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'middleware.log',
            'formatter': 'standard',
        },
    },
    'formatters': {
        'standard': {
            'format': '%(asctime)s - %(levelname)s - %(name)s: %(message)s',
        },
    },
    'loggers': {
        'user.middleware': {  # Asegúrate de usar el nombre del módulo del middleware
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # Cuando una vista de la API devuelve una respuesta, DRF la convierte en un formato JSON
        'rest_framework.renderers.BrowsableAPIRenderer',  # Desactivar en producción este es principalmente para depurar la API
        #'rest_framework_xml.renderers.XMLRenderer',  # Para respuestas en XML
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Autenticación basada en token
    #    'rest_framework.authentication.SessionAuthentication', #Luego de agregar el DJOSER
    ],
    #'DEFAULT_PERMISSION_CLASSES': [
    #    'rest_framework.permissions.IsAuthenticated',  # Por defecto, requiere autenticación desactivar o activar para pedir que siempre esten autentificados
    #],
    'DEFAULT_THROTTLE_RATES': {
        'anon':'5/day',
        'user':'10/day',
        'ten':'10/hour',
    },

}

# Utilizar el backend por defecto que almacena las sesiones en la base de datos
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Nombre de la cookie de sesión
SESSION_COOKIE_NAME = 'sessionid'

# Duración de la cookie de sesión en segundos (2 semanas)
SESSION_COOKIE_AGE = 1209600  # 2 semanas

# Guardar la sesión en cada solicitud (asegura que se persista cualquier cambio)
SESSION_SAVE_EVERY_REQUEST = True

# Si quieres que la sesión expire al cerrar el navegador, cambia esto a True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Opcional: Cookies seguras (recomendado para producción con HTTPS)
SESSION_COOKIE_SECURE = False  # Cambia a True si usas HTTPS