# Generated by Django 4.2.7 on 2024-01-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esquema', '0001_initial'),
        ('proyecto', '0018_tipoperfil_esquema_bono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='autorizacion_solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='revision.estado')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esquema.solicitud')),
                ('tipo_perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipoperfil')),
            ],
        ),
    ]
