# Generated by Django 4.2.9 on 2024-02-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0012_alter_status_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.costo')),
            ],
        ),
        migrations.CreateModel(
            name='Retardos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_sin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_goce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
        migrations.CreateModel(
            name='Incapacidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
        migrations.CreateModel(
            name='Domingo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
        migrations.CreateModel(
            name='Descanso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
        migrations.CreateModel(
            name='Castigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
    ]
