# Generated by Django 4.2.7 on 2024-03-24 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import prenomina.models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='url',
            field=models.FileField(default='', unique=True, upload_to='bonos/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='url',
            field=models.FileField(default='', unique=True, upload_to='bonos/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permiso_goce',
            name='url',
            field=models.FileField(default='', unique=True, upload_to='bonos/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permiso_sin',
            name='url',
            field=models.FileField(default='', unique=True, upload_to='bonos/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Dia_extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.FileField(unique=True, upload_to='bonos/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('editado', models.CharField(blank=True, max_length=100)),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
    ]
