# Generated by Django 4.2.9 on 2024-04-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0003_alter_comision_url_alter_dia_extra_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidades',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
