# Generated by Django 4.2.9 on 2024-04-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0004_incapacidades_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso_goce',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
