# Generated by Django 4.2.9 on 2024-04-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0006_permiso_sin_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='castigos',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
