# Generated by Django 4.2.9 on 2024-05-10 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0009_tipo_incapacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidades',
            name='subsecuente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.tipo_incapacidad'),
        ),
    ]
