# Generated by Django 4.2.9 on 2024-05-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0029_alter_historicalbonos_options_and_more'),
        ('prenomina', '0010_incapacidades_subsecuente_incapacidades_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aguinaldo_Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aguinaldo', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('fecha', models.DateField(null=True)),
                ('catorcena', models.IntegerField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.costo')),
            ],
        ),
    ]
