# Generated by Django 4.2.9 on 2024-05-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0011_aguinaldo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='aguinaldo_contrato',
            name='mes',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
