# Generated by Django 4.2.7 on 2024-05-19 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0030_alter_historicalbonos_options_and_more'),
        ('prenomina', '0012_aguinaldo_contrato_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='castigos',
            name='dia_inhabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='dia_inhabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion'),
        ),
        migrations.AddField(
            model_name='permiso_goce',
            name='dia_inhabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion'),
        ),
        migrations.AddField(
            model_name='permiso_sin',
            name='dia_inhabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion'),
        ),
    ]
