# Generated by Django 4.2.9 on 2024-05-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0013_castigos_dia_inhabil_incapacidades_dia_inhabil_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='castigos',
            index=models.Index(fields=['fecha'], name='prenomina_c_fecha_a81027_idx'),
        ),
        migrations.AddIndex(
            model_name='castigos',
            index=models.Index(fields=['fecha_fin'], name='prenomina_c_fecha_f_0b9eb8_idx'),
        ),
    ]
