# Generated by Django 4.2.9 on 2024-05-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0014_castigos_prenomina_c_fecha_a81027_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='descanso',
            index=models.Index(fields=['fecha'], name='prenomina_d_fecha_b837a0_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso_goce',
            index=models.Index(fields=['fecha'], name='prenomina_p_fecha_09bc77_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso_goce',
            index=models.Index(fields=['fecha_fin'], name='prenomina_p_fecha_f_aa53fa_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso_sin',
            index=models.Index(fields=['fecha'], name='prenomina_p_fecha_0b78b9_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso_sin',
            index=models.Index(fields=['fecha_fin'], name='prenomina_p_fecha_f_6f8955_idx'),
        ),
        migrations.AddIndex(
            model_name='retardos',
            index=models.Index(fields=['fecha'], name='prenomina_r_fecha_a7bbc3_idx'),
        ),
    ]
