# Generated by Django 4.2.9 on 2024-05-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0031_alter_historicalbonos_options_and_more'),
        ('prenomina', '0016_remove_castigos_dia_inhabil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenomina',
            name='fecha',
        ),
        migrations.AddField(
            model_name='prenomina',
            name='catorcena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.catorcenas'),
        ),
    ]
