# Generated by Django 4.2.9 on 2024-05-28 19:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import prenomina.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0032_alter_catorcenas_fecha_final_and_more'),
        ('prenomina', '0017_remove_prenomina_fecha_prenomina_catorcena'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncapacidadesRango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('soporte', models.FileField(unique=True, upload_to='prenomina/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xlsx', 'xls'])])),
                ('complete', models.BooleanField(default=False)),
                ('subsecuente', models.BooleanField(default=False)),
                ('dia_inhabil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pagar_incapcidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_pagados', models.IntegerField()),
                ('subsecuente', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('incapacidades_rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.incapacidadesrango')),
                ('prenomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciasRango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('soporte', models.FileField(unique=True, upload_to='prenomina/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xlsx', 'xls'])])),
                ('complete', models.BooleanField(default=False)),
                ('dia_inhabil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidencia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='incapacidadesrango',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidencia'),
        ),
    ]
