# Generated by Django 4.2.9 on 2024-05-28 20:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import prenomina.models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0018_incapacidadesrango_incidencia_pagar_incapcidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenominaIncidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('soporte', models.FileField(unique=True, upload_to='prenomina/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xlsx', 'xls'])])),
                ('incapacidades_rango', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.incapacidadesrango')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidencia')),
                ('incidencias_rango', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidenciasrango')),
                ('prenomina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
    ]
