# Generated by Django 4.2.9 on 2024-05-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0019_prenominaincidencias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pagar_incapcidad',
            new_name='pagar_incapacidad',
        ),
    ]
