# Generated by Django 4.2.9 on 2024-05-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0020_rename_pagar_incapcidad_pagar_incapacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='slug',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
