# Generated by Django 4.2.9 on 2024-05-29 19:38

import django.core.validators
from django.db import migrations, models
import prenomina.models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0021_incidencia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='soporte',
            field=models.FileField(null=True, unique=True, upload_to='prenomina/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xlsx', 'xls'])]),
        ),
    ]
