# Generated by Django 4.2.9 on 2024-05-29 20:20

import django.core.validators
from django.db import migrations, models
import prenomina.models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0022_alter_prenominaincidencias_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='soporte',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='prenomina/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xlsx', 'xls'])]),
        ),
    ]
