# Generated by Django 4.2.9 on 2024-05-29 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import prenomina.models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0023_alter_prenominaincidencias_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='prenomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina'),
        ),
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='soporte',
            field=models.FileField(blank=True, null=True, upload_to='prenomina/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xlsx', 'xls'])]),
        ),
    ]
