# Generated by Django 4.2.9 on 2024-05-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0024_alter_prenominaincidencias_prenomina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='prenomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='prenomina.prenomina'),
        ),
    ]
