# Generated by Django 4.2.9 on 2024-06-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0033_alter_economicos_dia_tomado_fecha_and_more'),
        ('prenomina', '0025_alter_prenominaincidencias_prenomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incapacidadesrango',
            name='dia_inhabil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion'),
        ),
        migrations.AlterField(
            model_name='incidenciasrango',
            name='dia_inhabil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion'),
        ),
    ]
