# Generated by Django 4.2.9 on 2024-06-06 00:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import prenomina.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0033_alter_economicos_dia_tomado_fecha_and_more'),
        ('prenomina', '0026_alter_incapacidadesrango_dia_inhabil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaRango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('soporte', models.FileField(unique=True, upload_to='prenomina/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xlsx', 'xls'])])),
                ('subsecuente', models.BooleanField(default=None, null=True)),
                ('complete', models.BooleanField(default=None)),
                ('dia_inhabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='PagarIncapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_pagados', models.IntegerField()),
                ('complete', models.BooleanField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='incidenciasrango',
            name='dia_inhabil',
        ),
        migrations.RemoveField(
            model_name='incidenciasrango',
            name='incidencia',
        ),
        migrations.RemoveField(
            model_name='pagar_incapacidad',
            name='incapacidades_rango',
        ),
        migrations.RemoveField(
            model_name='pagar_incapacidad',
            name='prenomina',
        ),
        migrations.RemoveField(
            model_name='prenominaincidencias',
            name='incapacidades_rango',
        ),
        migrations.RemoveField(
            model_name='prenominaincidencias',
            name='incidencias_rango',
        ),
        migrations.AddField(
            model_name='prenominaincidencias',
            name='complete',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='prenomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina'),
        ),
        migrations.DeleteModel(
            name='IncapacidadesRango',
        ),
        migrations.DeleteModel(
            name='IncidenciasRango',
        ),
        migrations.DeleteModel(
            name='pagar_incapacidad',
        ),
        migrations.AddField(
            model_name='pagarincapacidad',
            name='prenomina_incidencias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagar_incapacidad', to='prenomina.prenominaincidencias'),
        ),
        migrations.AddField(
            model_name='incidenciarango',
            name='prenomina_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenominaincidencias'),
        ),
    ]
