# Generated by Django 4.2.9 on 2024-06-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0027_incidenciarango_pagarincapacidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenciarango',
            name='dia_inhabil',
        ),
        migrations.RemoveField(
            model_name='incidenciarango',
            name='incidencia',
        ),
        migrations.RemoveField(
            model_name='incidenciarango',
            name='prenomina_incidencia',
        ),
        migrations.RemoveField(
            model_name='pagarincapacidad',
            name='prenomina_incidencias',
        ),
        migrations.RemoveField(
            model_name='prenominaincidencias',
            name='incidencia',
        ),
        migrations.RemoveField(
            model_name='prenominaincidencias',
            name='prenomina',
        ),
        migrations.DeleteModel(
            name='Incidencia',
        ),
        migrations.DeleteModel(
            name='IncidenciaRango',
        ),
        migrations.DeleteModel(
            name='PagarIncapacidad',
        ),
        migrations.DeleteModel(
            name='PrenominaIncidencias',
        ),
    ]
