# Generated by Django 4.2.9 on 2024-06-06 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import prenomina.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0033_alter_economicos_dia_tomado_fecha_and_more'),
        ('prenomina', '0030_remove_incidenciarango_dia_inhabil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaRango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('soporte', models.FileField(unique=True, upload_to='prenomina/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xlsx', 'xls'])])),
                ('subsecuente', models.BooleanField(default=None, null=True)),
                ('complete', models.BooleanField(default=None)),
                ('dia_inhabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='PrenominaIncidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='prenomina/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xlsx', 'xls'])])),
                ('complete', models.BooleanField(default=None)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidencia')),
                ('incidencia_rango', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidenciarango')),
                ('prenomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
            ],
        ),
    ]
