# Generated by Django 4.2.9 on 2024-06-06 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0031_incidencia_incidenciarango_prenominaincidencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='incidencia_rango',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidenciarango'),
        ),
    ]
