# Generated by Django 4.2.9 on 2024-06-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0032_alter_prenominaincidencias_incidencia_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciarango',
            name='complete',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='complete',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
