# Generated by Django 4.2.9 on 2024-06-08 18:04

import django.core.validators
from django.db import migrations, models
import prenomina.models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0034_alter_incidenciarango_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciarango',
            name='soporte',
            field=models.FileField(unique=True, upload_to='prenomina/', validators=[prenomina.models.validar_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'xlsx', 'xls'])]),
        ),
    ]
