# Generated by Django 4.2.9 on 2024-06-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0037_alter_historicalbonos_options_and_more'),
        ('prenomina', '0035_alter_incidenciarango_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciarango',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.costo'),
        ),
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='incidencia_rango',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenominaincidencias', to='prenomina.incidenciarango'),
        ),
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='prenomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='prenomina.prenomina'),
        ),
    ]
