# Generated by Django 4.2.9 on 2024-06-11 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0035_alter_incidenciarango_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='incidencia_rango',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenomina_incidencias', to='prenomina.incidenciarango'),
        ),
    ]
