# Generated by Django 4.2.7 on 2024-06-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0036_alter_prenominaincidencias_incidencia_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='incidencia_rango',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidenciarango'),
        ),
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='prenomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='prenomina.prenomina'),
        ),
    ]
