# Generated by Django 4.2.7 on 2024-06-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0037_alter_prenominaincidencias_incidencia_rango_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='incidencia_rango',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenominaincidencias', to='prenomina.incidenciarango'),
        ),
    ]
