# Generated by Django 4.2.9 on 2024-06-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0035_alter_historicalbonos_options_and_more'),
        ('prenomina', '0037_alter_prenominaincidencias_incidencia_rango_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciarango',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.costo'),
        ),
        migrations.AlterField(
            model_name='prenominaincidencias',
            name='prenomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina'),
        ),
    ]
