# Generated by Django 4.2.9 on 2024-01-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0004_alter_nivel_options'),
        ('esquema', '0003_rename_nombre_puesto_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AutorizarSolicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisar.estado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esquema.solicitud')),
                ('tipo_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipoperfil')),
            ],
        ),
    ]
