# Generated by Django 4.2.9 on 2024-02-06 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0005_rename_complete_requerimieto_solicitud_complete_and_more'),
        ('revisar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizarsolicitudes',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizarsolicitudes', to='esquema.solicitud'),
        ),
    ]
