# Generated by Django 4.2.9 on 2024-02-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar', '0002_alter_autorizarsolicitudes_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizarsolicitudes',
            name='revisar',
            field=models.BooleanField(default=False),
        ),
    ]
