# Generated by Django 4.2.9 on 2024-02-21 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_vacaciones_dias_tomados_economicos_dia_tomado'),
        ('prenomina', '0001_initial'),
        ('revisar', '0003_autorizarsolicitudes_revisar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizarPrenomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revisar.estado')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil')),
                ('prenomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina.prenomina')),
                ('tipo_perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipoperfil')),
            ],
        ),
    ]
